### ISSUE TITLE
Add client ID in the returned value

### ISSUE THREAD

**Issue by johnbalvin** [futurenda/google-auth-id-token-verifier#6]
I node.js when doing the verification I can get the user id 
`const id= ticket.getPayload()['sub'];`

but in this library this value does not exists

**Comment by johnbalvin** [comment]
don't need the library anymore, just by making a HTTP request to endpoint:

`https://oauth2.googleapis.com/tokeninfo`

with the query id_token.
You will get a JSON object with all the info as anwser
example:
let's say I have the token: ajsndasdasdba , you will need to make a GET request to url:

`https://oauth2.googleapis.com/tokeninfo?id_token=ajsndasdasdba`

You will receive a JSON object with all the info

**Comment by mununki** [comment]
@johnbalvin The approach of this library is still vaild. Because calling the `tokeninfo` api is not suitable for production where the doc states https://developers.google.com/identity/sign-in/web/backend-auth#calling-the-tokeninfo-endpoint

> It is not suitable for use in production code as requests may be throttled or otherwise subject to intermittent errors.
